import type { VercelRequest, VercelResponse } from '@vercel/node';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const manifestPaths = Array.from(new Set([
  path.join(process.cwd(), 'public', 'doodles', 'manifest.json'),
  path.join(process.cwd(), 'dist', 'doodles', 'manifest.json'),
  path.join(__dirname, '..', 'public', 'doodles', 'manifest.json'),
  path.join(__dirname, '..', 'dist', 'doodles', 'manifest.json')
]));

const staticImagePattern = /^\/doodles\/[a-z0-9._-]+\.(png|jpe?g|webp|gif|svg)$/i;
let manifestCache: { updated_at?: string; count?: number; doodles?: any[] } | null = null;

async function readManifest() {
  if (manifestCache?.doodles?.length) return manifestCache;

  for (const manifestPath of manifestPaths) {
    try {
      const raw = await readFile(manifestPath, 'utf8');
      const payload = JSON.parse(raw);

      if (Array.isArray(payload?.doodles)) {
        manifestCache = payload;
        return payload;
      }
    } catch {
      // Try the next bundled path.
    }
  }

  return { count: 0, doodles: [] };
}

function requestPath(req: VercelRequest) {
  const host = req.headers.host || 'localhost';
  return new URL(req.url || '/', `https://${host}`).pathname;
}

function isLocalDoodleImage(value: string) {
  return staticImagePattern.test(value);
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  const pathname = requestPath(req);

  if (pathname === '/api/visitor-timezone') {
    res.status(200).json({ timeZone: null, source: 'browser-fallback' });
    return;
  }

  if (pathname === '/api/doodle/image') {
    const imageUrl = String(req.query.url || '');

    if (isLocalDoodleImage(imageUrl)) {
      res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
      res.setHeader('Location', imageUrl);
      res.status(307).end();
      return;
    }

    res.status(400).json({ error: 'Unsupported doodle image URL' });
    return;
  }

  if (!pathname.startsWith('/api/doodle/')) {
    res.status(404).json({ error: 'Not found' });
    return;
  }

  const manifest = await readManifest();
  const doodles = manifest.doodles || [];

  if (pathname === '/api/doodle/history') {
    res.setHeader('Cache-Control', 'public, max-age=0, must-revalidate');
    res.status(doodles.length ? 200 : 404).json(doodles.length ? doodles : { error: 'No doodles found' });
    return;
  }

  if (pathname === '/api/doodle/latest') {
    res.setHeader('Cache-Control', 'public, max-age=0, must-revalidate');
    res.status(doodles[0] ? 200 : 404).json(doodles[0] || { error: 'No doodles found' });
    return;
  }

  if (pathname === '/api/doodle/health') {
    res.setHeader('Cache-Control', 'public, max-age=0, must-revalidate');
    res.status(doodles.length ? 200 : 503).json({
      ok: doodles.length > 0,
      checkedAt: new Date().toISOString(),
      source: doodles.length ? 'static-manifest' : 'none',
      localFallback: {
        ok: doodles.length > 0,
        count: doodles.length,
        latest: doodles[0]?.name || null
      },
      manifest: {
        updatedAt: manifest.updated_at || null,
        count: manifest.count || doodles.length
      }
    });
    return;
  }

  if (pathname === '/api/doodle/refresh') {
    res.setHeader('Cache-Control', 'no-store');
    res.status(doodles.length ? 200 : 503).json({
      ok: doodles.length > 0,
      source: doodles.length ? 'static-manifest' : 'none',
      refreshedAt: manifest.updated_at || null,
      count: doodles.length,
      latest: doodles[0]?.name || null,
      note: 'Archive updates are generated by GitHub Actions and served as static files.'
    });
    return;
  }

  res.status(404).json({ error: 'Not found' });
}
